# Configuracion del Proyecto de Reconocimiento de Caracteres

# Configuracion de la red neuronal
network_config:
  capas: [512, 384, 256, 128]  # Red mas profunda para mejor discriminacion
  activaciones: ['relu', 'relu', 'relu', 'relu', 'softmax']
  oculta_neuronas: 512
  tasa_aprendizaje: 0.0008  # Balance entre velocidad y estabilidad
  lambda_l2: 0.00001
  dropout_rate: 0.1  # Menos dropout para mas confianza
  tamano_lote: 32
  epocas: 350  # Mas epocas para convergencia completa

  # BatchNormalization - Normaliza activaciones entre capas
  use_batch_norm: true

  # Early Stopping - Detiene entrenamiento si no mejora
  early_stopping_patience: 25  # Mas paciencia para encontrar mejor modelo
  early_stopping_min_delta: 0.0003  # Mas sensible a mejoras pequenas

# Learning Rate Scheduling - Reduce tasa de aprendizaje progresivamente
lr_scheduler_config:
  tipo: step_decay
  tasa_decaimento: 0.5
  epocas_decaimento: 50  # Decay cada 50 epocas para aprendizaje mas suave

# Configuracion de datos
data_config:
  tamano_imagen: [28, 28]
  usar_augmentacion: true
  semilla: 42

# Configuracion de aumento de datos (AGRESIVO - para reconocer dibujos a mano con variaciones)
augmentation_config:
  rango_rotacion: 15  # ±15 grados para soportar inclinaciones
  desplazamiento_horizontal: 0.15  # 15% de desplazamiento
  desplazamiento_vertical: 0.15  # 15% de desplazamiento
  rango_zoom: 0.15  # Zoom ±15%
  voltear_horizontal: false  # No voltear letras (cambiaría significado)
  voltear_vertical: false
  radio_blur: 0.5  # Blur moderado para simular trazos imperfectos
  nivel_ruido: 0.03  # Ruido moderado

# Rutas del proyecto
paths:
  datos_crudos: 'data/raw'
  datos_procesados: 'data/processed'
  modelos: 'models'
  logs: 'logs'

# Configuracion de logging
logging_config:
  nivel: 'INFO'
  formato: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# Etiquetas personalizadas (A-Z mayusculas, a-z minusculas, 0-9 numeros, y caracteres especiales)
custom_labels:
  # Mayusculas A-Z
  - 'A'
  - 'B'
  - 'C'
  - 'D'
  - 'E'
  - 'F'
  - 'G'
  - 'H'
  - 'I'
  - 'J'
  - 'K'
  - 'L'
  - 'M'
  - 'N'
  - 'O'
  - 'P'
  - 'Q'
  - 'R'
  - 'S'
  - 'T'
  - 'U'
  - 'V'
  - 'W'
  - 'X'
  - 'Y'
  - 'Z'
  # Minusculas a-z
  - 'a'
  - 'b'
  - 'c'
  - 'd'
  - 'e'
  - 'f'
  - 'g'
  - 'h'
  - 'i'
  - 'j'
  - 'k'
  - 'l'
  - 'm'
  - 'n'
  - 'o'
  - 'p'
  - 'q'
  - 'r'
  - 's'
  - 't'
  - 'u'
  - 'v'
  - 'w'
  - 'x'
  - 'y'
  - 'z'
  # Numeros 0-9
  - '0'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  # Caracteres especiales comunes
  - '!'
  - '@'
  - '#'
  - '$'
  - '%'
  - '&'
  - '*'
  - '('
  - ')'
  - '-'
  - '_'
  - '+'
  - '='
  - '['
  - ']'
  - '{'
  - '}'
  - ';'
  - ':'
  - "'"
  - '"'
  - ','
  - '.'
  - '<'
  - '>'
  - '/'
  - '?'
  - '|'
  - '~'
  - '`'
  - '¡'
  - '¿'

