# Configuracion del Proyecto de Reconocimiento de Caracteres

# Configuracion de la red neuronal
network_config:
  capas: [512, 384, 256, 128]  # Red mas profunda para mejor discriminacion
  activaciones: ['relu', 'relu', 'relu', 'relu', 'softmax']
  oculta_neuronas: 512
  tasa_aprendizaje: 0.0008  # Balance entre velocidad y estabilidad
  lambda_l2: 0.00001
  dropout_rate: 0.1  # Menos dropout para mas confianza
  tamano_lote: 32
  epocas: 350  # Mas epocas para convergencia completa

  # BatchNormalization - Normaliza activaciones entre capas
  use_batch_norm: true

  # Early Stopping - Detiene entrenamiento si no mejora
  early_stopping_patience: 25  # Mas paciencia para encontrar mejor modelo
  early_stopping_min_delta: 0.0003  # Mas sensible a mejoras pequenas

# Learning Rate Scheduling - Reduce tasa de aprendizaje progresivamente
lr_scheduler_config:
  tipo: step_decay
  tasa_decaimento: 0.5
  epocas_decaimento: 50  # Decay cada 50 epocas para aprendizaje mas suave

# Configuracion de datos
data_config:
  tamano_imagen: [28, 28]
  usar_augmentacion: true
  semilla: 42

# Configuracion de aumento de datos (MINIMO - solo variaciones naturales)
augmentation_config:
  rango_rotacion: 8  # ±8 grados (mas conservador)
  desplazamiento_horizontal: 0.06
  desplazamiento_vertical: 0.06
  rango_zoom: 0.06
  voltear_horizontal: false
  voltear_vertical: false
  radio_blur: 0.2  # Blur muy sutil
  nivel_ruido: 0.01  # Ruido minimo

# Rutas del proyecto
paths:
  datos_crudos: 'data/raw'
  datos_procesados: 'data/processed'
  modelos: 'models'
  logs: 'logs'

# Configuracion de logging
logging_config:
  nivel: 'INFO'
  formato: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# Etiquetas personalizadas (A-Z mayusculas y a-z minusculas)
custom_labels:
  - 'A'
  - 'B'
  - 'C'
  - 'D'
  - 'E'
  - 'F'
  - 'G'
  - 'H'
  - 'I'
  - 'J'
  - 'K'
  - 'L'
  - 'M'
  - 'N'
  - 'O'
  - 'P'
  - 'Q'
  - 'R'
  - 'S'
  - 'T'
  - 'U'
  - 'V'
  - 'W'
  - 'X'
  - 'Y'
  - 'Z'
  - 'a'
  - 'b'
  - 'c'
  - 'd'
  - 'e'
  - 'f'
  - 'g'
  - 'h'
  - 'i'
  - 'j'
  - 'k'
  - 'l'
  - 'm'
  - 'n'
  - 'o'
  - 'p'
  - 'q'
  - 'r'
  - 's'
  - 't'
  - 'u'
  - 'v'
  - 'w'
  - 'x'
  - 'y'
  - 'z'

