# Configuracion del Proyecto de Reconocimiento de Caracteres

# Configuracion de la red neuronal
network_config:
  capas: [512, 256, 128]  # Capas ocultas (entrada y salida se añaden automáticamente)
  activaciones: ['relu', 'relu', 'relu', 'softmax']  # 3 ocultas + 1 salida = 4
  oculta_neuronas: 512
  tasa_aprendizaje: 0.001  # Reducido para convergencia más estable
  lambda_l2: 0.00005  # Más regularización para evitar overfitting
  dropout_rate: 0.2  # Más dropout para generalización
  tamano_lote: 32  # Reducido para evitar problemas de memoria

  epocas: 500  # Más épocas con early stopping fuerte

  # BatchNormalization - Normaliza activaciones entre capas
  use_batch_norm: true

  # Early Stopping - Detiene entrenamiento si no mejora
  early_stopping_patience: 35  # Más paciencia
  early_stopping_min_delta: 0.0001  # Más sensible

# Learning Rate Scheduling - Reduce tasa de aprendizaje progresivamente
lr_scheduler_config:
  tipo: step_decay
  tasa_decaimento: 0.7  # Decay más suave (antes 0.5)
  epocas_decaimento: 40  # Decay cada 40 épocas

# Configuracion de datos
data_config:
  tamano_imagen: [28, 28]
  usar_augmentacion: true  # REACTIVADO para mejor generalización
  semilla: 42

# Configuracion de aumento de datos (MUY AGRESIVO - simula escritura a mano real)
augmentation_config:
  rango_rotacion: 20  # ±20 grados (antes 15) - soporta más inclinaciones
  desplazamiento_horizontal: 0.2  # 20% (antes 15%)
  desplazamiento_vertical: 0.2  # 20% (antes 15%)
  rango_zoom: 0.2  # Zoom ±20% (antes 15%)
  voltear_horizontal: false  # No voltear letras
  voltear_vertical: false
  radio_blur: 1.0  # Blur más fuerte (antes 0.5) - simula trazos imperfectos
  nivel_ruido: 0.05  # Más ruido (antes 0.03) - simula variaciones de dibujo

# Rutas del proyecto
paths:
  datos_crudos: 'data/raw'
  datos_procesados: 'data/processed'
  modelos: 'models'
  logs: 'logs'

# Configuracion de logging
logging_config:
  nivel: 'INFO'
  formato: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# Etiquetas personalizadas (A-Z mayusculas, a-z minusculas, 0-9 numeros, y caracteres especiales)
custom_labels:
  # Mayusculas A-Z
  - 'A'
  - 'B'
  - 'C'
  - 'D'
  - 'E'
  - 'F'
  - 'G'
  - 'H'
  - 'I'
  - 'J'
  - 'K'
  - 'L'
  - 'M'
  - 'N'
  - 'O'
  - 'P'
  - 'Q'
  - 'R'
  - 'S'
  - 'T'
  - 'U'
  - 'V'
  - 'W'
  - 'X'
  - 'Y'
  - 'Z'
  # Minusculas a-z
  - 'a'
  - 'b'
  - 'c'
  - 'd'
  - 'e'
  - 'f'
  - 'g'
  - 'h'
  - 'i'
  - 'j'
  - 'k'
  - 'l'
  - 'm'
  - 'n'
  - 'o'
  - 'p'
  - 'q'
  - 'r'
  - 's'
  - 't'
  - 'u'
  - 'v'
  - 'w'
  - 'x'
  - 'y'
  - 'z'
  # Numeros 0-9
  - '0'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  # Caracteres especiales comunes
  - '!'
  - '@'
  - '#'
  - '$'
  - '%'
  - '&'
  - '*'
  - '('
  - ')'
  - '-'
  - '_'
  - '+'
  - '='
  - '['
  - ']'
  - '{'
  - '}'
  - ';'
  - ':'
  - "'"
  - '"'
  - ','
  - '.'
  - '<'
  - '>'
  - '/'
  - '?'
  - '|'
  - '~'
  - '`'
  - '¡'
  - '¿'

