# Configuración del Proyecto de Reconocimiento de Caracteres

# Configuración de la red neuronal
network_config:
  capas: [256, 128, 64]  # Más capas y neuronas
  activaciones: ['relu', 'relu', 'relu', 'softmax']  # Funciones de activación
  oculta_neuronas: 256  # Neuronas en capa oculta (fallback)
  tasa_aprendizaje: 0.0005  # Tasa de aprendizaje más baja para mejor convergencia
  lambda_l2: 0.00001  # Regularización L2 reducida
  dropout_rate: 0.2  # Menos dropout para aprender mejor
  tamano_lote: 32  # Lotes más pequeños para mejor generalización
  epocas: 200  # Más épocas para mejor entrenamiento

  # BatchNormalization - Normaliza activaciones entre capas
  use_batch_norm: true  # ✅ ACTIVADO

  # Early Stopping - Detiene entrenamiento si no mejora
  early_stopping_patience: 15  # ✅ ACTIVADO - Espera 15 épocas sin mejora
  early_stopping_min_delta: 0.001  # ✅ ACTIVADO - Mejora mínima requerida

# Learning Rate Scheduling - Reduce tasa de aprendizaje progresivamente
lr_scheduler_config:
  tipo: step_decay  # ✅ ACTIVADO - Tipo de scheduler
  tasa_decaimento: 0.5  # ✅ ACTIVADO - Reduce LR a la mitad
  epocas_decaimento: 30  # ✅ ACTIVADO - Cada 30 épocas

# Configuración de datos
data_config:
  tamano_imagen: [28, 28]  # Alto x Ancho
  usar_augmentacion: true
  semilla: 42

# Configuración de aumento de datos (Data Augmentation más agresivo)
augmentation_config:
  rango_rotacion: 30  # Rotación más agresiva: ±30 grados
  desplazamiento_horizontal: 0.1
  desplazamiento_vertical: 0.1
  rango_zoom: 0.1
  voltear_horizontal: false
  voltear_vertical: false
  radio_blur: 1.5  # Desenfoque gaussiano con radio hasta 1.5
  nivel_ruido: 0.2  # Ruido gaussiano con nivel 0.2

# Rutas del proyecto
paths:
  datos_crudos: 'data/raw'
  datos_procesados: 'data/processed'
  modelos: 'models'
  logs: 'logs'

# Configuración de logging
logging_config:
  nivel: 'INFO'
  formato: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# Etiquetas personalizadas (A-Z mayúsculas y a-z minúsculas)
custom_labels:
  - 'A'
  - 'B'
  - 'C'
  - 'D'
  - 'E'
  - 'F'
  - 'G'
  - 'H'
  - 'I'
  - 'J'
  - 'K'
  - 'L'
  - 'M'
  - 'N'
  - 'O'
  - 'P'
  - 'Q'
  - 'R'
  - 'S'
  - 'T'
  - 'U'
  - 'V'
  - 'W'
  - 'X'
  - 'Y'
  - 'Z'
  - 'a'
  - 'b'
  - 'c'
  - 'd'
  - 'e'
  - 'f'
  - 'g'
  - 'h'
  - 'i'
  - 'j'
  - 'k'
  - 'l'
  - 'm'
  - 'n'
  - 'o'
  - 'p'
  - 'q'
  - 'r'
  - 's'
  - 't'
  - 'u'
  - 'v'
  - 'w'
  - 'x'
  - 'y'
  - 'z'
